/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSong.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\FontSong.txt     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_4E00[ 32] = { /* code 4E00, <CJK Ideograph, First> */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_4E0A[ 32] = { /* code 4E0A */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_4E0B[ 32] = { /* code 4E0B */
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,_X______,
  ______X_,__X_____,
  ______X_,___X____,
  ______X_,____X___,
  ______X_,____X___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_4EBA[ 32] = { /* code 4EBA */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___,
  _X______,_____X__,
  X_______,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_4F4D[ 32] = { /* code 4F4D */
  ____X___,X_______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,________,
  ___X_XXX,XXXXXX__,
  __XX____,________,
  __XX____,____X___,
  _X_X__X_,____X___,
  X__X__X_,____X___,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,__X_____,
  ___X____,__X_____,
  ___XXXXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_4F53[ 32] = { /* code 4F53 */
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,_X______,
  ___X_XXX,XXXXXX__,
  __XX____,_X______,
  __XX____,XXX_____,
  _X_X____,XXX_____,
  X__X___X,_X_X____,
  ___X___X,_X_X____,
  ___X__X_,_X__X___,
  ___X_X_X,XXXX_X__,
  ___XX___,_X____X_,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_505C[ 32] = { /* code 505C */
  ___X____,X_______,
  ___X____,_X______,
  ___X_XXX,XXXXXX__,
  __X_____,________,
  __X___XX,XXXXX___,
  _XX___X_,____X___,
  _XX___XX,XXXXX___,
  X_X_____,________,
  __X_XXXX,XXXXXXX_,
  __X_X___,______X_,
  __X___XX,XXXXX___,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  __X____X,_X______,
  __X_____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5149[ 32] = { /* code 5149 */
  _______X,________,
  __X____X,____X___,
  ___X___X,____X___,
  ____X__X,___X____,
  ____X__X,__X_____,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,_X____X_,
  ____X___,_X____X_,
  ___X____,_X____X_,
  __X_____,__XXXXX_,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_53D7[ 32] = { /* code 53D7 */
  ________,____X___,
  _______X,XXXXXX__,
  _XXXXXX_,___X____,
  __X___X_,___X____,
  ___X___X,__X_____,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  __XXXXXX,XXXX____,
  ___X____,___X____,
  ____X___,__X_____,
  _____X__,_X______,
  ______XX,X_______,
  ____XX__,_XX_____,
  __XX____,___XX___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5668[ 32] = { /* code 5668 */
  ________,________,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__,
  _______X,__X_____,
  _______X,___X____,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  ____XX__,_XX_____,
  __XX____,___XX___,
  XX______,_____XX_,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_590D[ 32] = { /* code 590D */
  ___X____,________,
  ___X____,________,
  ___XXXXX,XXXXXX__,
  __X_____,________,
  _X_XXXXX,XXXX____,
  X__X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  _____X__,________,
  ____XXXX,XXXX____,
  ___XX___,__X_____,
  _XX__X__,_X______,
  ______XX,X_______,
  ___XXX__,_XXX____,
  XXX_____,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5916[ 32] = { /* code 5916 */
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  __XXXXX_,_X______,
  __X___X_,_XX_____,
  _X____X_,_X_X____,
  _X____X_,_X__X___,
  X_X__X__,_X___X__,
  ___X_X__,_X___X__,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,_X______,
  __X_____,_X______,
  _X______,_X______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5927[ 32] = { /* code 5927 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5B50[ 32] = { /* code 5B50 */
  ________,________,
  _XXXXXXX,XXXXX___,
  ________,___X____,
  ________,__X_____,
  ________,_X______,
  _______X,X_______,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5B99[ 32] = { /* code 5B99 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X______X,_____X__,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_5EA6[ 32] = { /* code 5EA6 */
  _______X,________,
  ________,X_______,
  __XXXXXX,XXXXXXX_,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __XXXXXX,XXXXXX__,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___XX,XXX_____,
  __X_____,________,
  __X_XXXX,XXXX____,
  __X__X__,___X____,
  _X____X_,__X_____,
  _X_____X,XX______,
  X____XX_,__XX____,
  __XXX___,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6062[ 32] = { /* code 6062 */
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X__XX,XXXXXXX_,
  ___XX___,X_______,
  _X_X_X__,X__X____,
  _X_X____,X__X____,
  _X_X___X,___X__X_,
  X__X___X,_X_X__X_,
  ___X___X,_X_X_X__,
  ___X__X_,X__X____,
  ___X__X_,__X_X___,
  ___X_X__,__X_X___,
  ___X____,_X___X__,
  ___X____,X____X__,
  ___X___X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6309[ 32] = { /* code 6309 */
  ___X____,_X______,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXX_,
  XXXXX_X_,______X_,
  ___X_X__,_X___X__,
  ___X____,_X______,
  ___XX_XX,XXXXXXX_,
  __XX____,X___X___,
  XX_X____,X___X___,
  ___X___X,____X___,
  ___X____,XX_X____,
  ___X____,__X_____,
  ___X____,_X_X____,
  _X_X____,X___X___,
  __X___XX,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_63A5[ 32] = { /* code 63A5 */
  ___X____,X_______,
  ___X____,_X______,
  ___X__XX,XXXXXX__,
  ___X____,________,
  XXXXXX_X,____X___,
  ___X____,X__X____,
  ___X_XXX,XXXXXXX_,
  ___X____,_X______,
  ___XX___,_X______,
  __XX_XXX,XXXXXXX_,
  XX_X____,X___X___,
  ___X___X,____X___,
  ___X____,X__X____,
  ___X____,_XX_____,
  _X_X___X,X__XX___,
  __X__XX_,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_654F[ 32] = { /* code 654F */
  _X______,__X_____,
  _X______,__X_____,
  _XXXXXXX,__X_____,
  X_______,__XXXXX_,
  _XXXXXX_,_X___X__,
  _X____X_,_X___X__,
  _X_X__X_,_X___X__,
  _X__X_X_,X_X__X__,
  XXXXXXXX,X_X_X___,
  _X____X_,__X_X___,
  X__X__X_,___X____,
  X___X_X_,___X____,
  XXXXXXXX,__X_X___,
  ______X_,_X__X___,
  ___X_X__,X____X__,
  ____X__X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_65CB[ 32] = { /* code 65CB */
  __X_____,X_______,
  ___X____,X_______,
  ___X____,XXXXXXX_,
  _______X,________,
  XXXXXXX_,________,
  __X____X,XXXXXX__,
  __X_____,__X__X__,
  __XXXX__,__X__X__,
  __X__X__,X_X_____,
  __X__X__,X_X_____,
  __X__X__,X_XXXX__,
  __X__X__,X_X_____,
  __X__X__,X_X_____,
  _X___X_X,_XX_____,
  _X_X_X_X,__XXXXX_,
  X___X_X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6682[ 32] = { /* code 6682 */
  ___X____,____XX__,
  XXXXXXX_,XXXX____,
  __X_____,X_______,
  _X__X___,X_______,
  _XXXXXX_,XXXXXXX_,
  ____X___,X___X___,
  ____XXX_,X___X___,
  XXXXX__X,____X___,
  _X__X_X_,____X___,
  ___XXXXX,XXXXX___,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6D4B[ 32] = { /* code 6D4B */
  ________,_____X__,
  __X__XXX,XX___X__,
  ___X_X__,_X___X__,
  ___X_X__,_X_X_X__,
  X____X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  __X__X_X,_X_X_X__,
  XXX__X_X,_X_X_X__,
  __X____X,_____X__,
  __X___X_,X____X__,
  __X___X_,_X___X__,
  __X__X__,___X_X__,
  ____X___,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6E29[ 32] = { /* code 6E29 */
  ________,________,
  __X___XX,XXXXX___,
  ___X__X_,____X___,
  ___X__X_,____X___,
  X_____XX,XXXXX___,
  _X____X_,____X___,
  _X____X_,____X___,
  ___X__XX,XXXXX___,
  ___X____,________,
  __X__XXX,XXXXXX__,
  XXX__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X_XXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_6E7F[ 32] = { /* code 6E7F */
  ________,________,
  __X__XXX,XXXXX___,
  ___X_X__,____X___,
  ___X_X__,____X___,
  X____XXX,XXXXX___,
  _X___X__,____X___,
  _X___X__,____X___,
  ___X_XXX,XXXXX___,
  ___X___X,__X_____,
  __X____X,__X_____,
  XXX_X__X,__X__X__,
  __X__X_X,__X_X___,
  __X___XX,__XX____,
  __X____X,__X_____,
  __X_XXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_7535[ 32] = { /* code 7535 */
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X_X_,
  _______X,______X_,
  _______X,______X_,
  ________,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_7EA2[ 32] = { /* code 7EA2 */
  ___X____,________,
  ___X____,________,
  __X____X,XXXXXX__,
  __X__X__,__X_____,
  _X___X__,__X_____,
  XXXXX___,__X_____,
  ___X____,__X_____,
  __X_____,__X_____,
  _X______,__X_____,
  XXXXXX__,__X_____,
  _X______,__X_____,
  ________,__X_____,
  ___XXX__,__X_____,
  XXX_____,__X_____,
  _X____XX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_84DD[ 32] = { /* code 84DD */
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  _____X__,X_______,
  __X__X__,X_______,
  __X__X__,XXXXXX__,
  __X__X__,X_X_____,
  __X__X_X,___X____,
  ________,________,
  __XXXXXX,XXXXX___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_8DDD[ 32] = { /* code 8DDD */
  ________,________,
  _XXXXX_X,XXXXXXX_,
  _X___X_X,________,
  _X___X_X,________,
  _X___X_X,________,
  _XXXXX_X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  _X_XXX_X,_____X__,
  _X_X___X,_____X__,
  _X_X___X,XXXXXX__,
  _X_X___X,________,
  _X_XXX_X,________,
  XXX____X,________,
  _______X,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_8F6C[ 32] = { /* code 8F6C */
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  XXXXXX_X,XXXXXX__,
  _X______,__X_____,
  _X_X____,_X______,
  X__X__XX,XXXXXXX_,
  XXXXXX__,_X______,
  ___X____,X_______,
  ___X___X,XXXXXX__,
  ___XXX__,_____X__,
  XXXX____,X___X___,
  _X_X____,_X_X____,
  ___X____,__X_____,
  ___X____,___X____,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_952E[ 32] = { /* code 952E */
  __X_____,___X____,
  __X_____,___X____,
  __XXX_XX,_XXXXX__,
  __X____X,___X_X__,
  _X_____X,XXXXXXX_,
  _XXXX_X_,___X_X__,
  X_X___X_,_XXXXX__,
  __X__XXX,___X____,
  XXXXX__X,_XXXXX__,
  __X__X_X,___X____,
  __X__X_X,XXXXXXX_,
  __X___X_,___X____,
  __X_X_X_,___X____,
  __XX_X_X,________,
  __X_X___,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_963B[ 32] = { /* code 963B */
  ________,________,
  _XXXXX_X,XXXXX___,
  _X___X_X,____X___,
  _X__X__X,____X___,
  _X__X__X,____X___,
  _X_X___X,XXXXX___,
  _X__X__X,____X___,
  _X__X__X,____X___,
  _X___X_X,____X___,
  _X___X_X,XXXXX___,
  _X___X_X,____X___,
  _XX_X__X,____X___,
  _X_X___X,____X___,
  _X_____X,____X___,
  _X___XXX,XXXXXXX_,
  _X______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong_9875[ 32] = { /* code 9875 */
  ________,________,
  _XXXXXXX,XXXXXX__,
  ______X_,________,
  _____X__,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X__X_,X__X____,
  ______X_,_X______,
  _____X__,__X_____,
  ___XX___,___X____,
  _XX_____,____X___};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontSong_CharInfo[33] = {
   {  16,  16,  2, acGUI_FontFontSong_4E00 } /* code 4E00 */
  ,{  16,  16,  2, acGUI_FontFontSong_4E0A } /* code 4E0A */
  ,{  16,  16,  2, acGUI_FontFontSong_4E0B } /* code 4E0B */
  ,{  16,  16,  2, acGUI_FontFontSong_4EBA } /* code 4EBA */
  ,{  16,  16,  2, acGUI_FontFontSong_4F4D } /* code 4F4D */
  ,{  16,  16,  2, acGUI_FontFontSong_4F53 } /* code 4F53 */
  ,{  16,  16,  2, acGUI_FontFontSong_505C } /* code 505C */
  ,{  16,  16,  2, acGUI_FontFontSong_5149 } /* code 5149 */
  ,{  16,  16,  2, acGUI_FontFontSong_53D7 } /* code 53D7 */
  ,{  16,  16,  2, acGUI_FontFontSong_5668 } /* code 5668 */
  ,{  16,  16,  2, acGUI_FontFontSong_590D } /* code 590D */
  ,{  16,  16,  2, acGUI_FontFontSong_5916 } /* code 5916 */
  ,{  16,  16,  2, acGUI_FontFontSong_5927 } /* code 5927 */
  ,{  16,  16,  2, acGUI_FontFontSong_5B50 } /* code 5B50 */
  ,{  16,  16,  2, acGUI_FontFontSong_5B99 } /* code 5B99 */
  ,{  16,  16,  2, acGUI_FontFontSong_5EA6 } /* code 5EA6 */
  ,{  16,  16,  2, acGUI_FontFontSong_6062 } /* code 6062 */
  ,{  16,  16,  2, acGUI_FontFontSong_6309 } /* code 6309 */
  ,{  16,  16,  2, acGUI_FontFontSong_63A5 } /* code 63A5 */
  ,{  16,  16,  2, acGUI_FontFontSong_654F } /* code 654F */
  ,{  16,  16,  2, acGUI_FontFontSong_65CB } /* code 65CB */
  ,{  16,  16,  2, acGUI_FontFontSong_6682 } /* code 6682 */
  ,{  16,  16,  2, acGUI_FontFontSong_6D4B } /* code 6D4B */
  ,{  16,  16,  2, acGUI_FontFontSong_6E29 } /* code 6E29 */
  ,{  16,  16,  2, acGUI_FontFontSong_6E7F } /* code 6E7F */
  ,{  16,  16,  2, acGUI_FontFontSong_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_FontFontSong_7EA2 } /* code 7EA2 */
  ,{  16,  16,  2, acGUI_FontFontSong_84DD } /* code 84DD */
  ,{  16,  16,  2, acGUI_FontFontSong_8DDD } /* code 8DDD */
  ,{  16,  16,  2, acGUI_FontFontSong_8F6C } /* code 8F6C */
  ,{  16,  16,  2, acGUI_FontFontSong_952E } /* code 952E */
  ,{  16,  16,  2, acGUI_FontFontSong_963B } /* code 963B */
  ,{  16,  16,  2, acGUI_FontFontSong_9875 } /* code 9875 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop32 = {
   0x9875 /* first character */
  ,0x9875 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 32] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop31 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 31] /* address of first character */
  ,&GUI_FontFontSong_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop30 = {
   0x952E /* first character */
  ,0x952E /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 30] /* address of first character */
  ,&GUI_FontFontSong_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop29 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 29] /* address of first character */
  ,&GUI_FontFontSong_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop28 = {
   0x8DDD /* first character */
  ,0x8DDD /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 28] /* address of first character */
  ,&GUI_FontFontSong_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop27 = {
   0x84DD /* first character */
  ,0x84DD /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 27] /* address of first character */
  ,&GUI_FontFontSong_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop26 = {
   0x7EA2 /* first character */
  ,0x7EA2 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 26] /* address of first character */
  ,&GUI_FontFontSong_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop25 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 25] /* address of first character */
  ,&GUI_FontFontSong_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop24 = {
   0x6E7F /* first character */
  ,0x6E7F /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 24] /* address of first character */
  ,&GUI_FontFontSong_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop23 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 23] /* address of first character */
  ,&GUI_FontFontSong_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop22 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 22] /* address of first character */
  ,&GUI_FontFontSong_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop21 = {
   0x6682 /* first character */
  ,0x6682 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 21] /* address of first character */
  ,&GUI_FontFontSong_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop20 = {
   0x65CB /* first character */
  ,0x65CB /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 20] /* address of first character */
  ,&GUI_FontFontSong_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop19 = {
   0x654F /* first character */
  ,0x654F /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFontSong_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop18 = {
   0x63A5 /* first character */
  ,0x63A5 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFontSong_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop17 = {
   0x6309 /* first character */
  ,0x6309 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFontSong_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop16 = {
   0x6062 /* first character */
  ,0x6062 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFontSong_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop15 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFontSong_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop14 = {
   0x5B99 /* first character */
  ,0x5B99 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFontSong_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop13 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFontSong_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop12 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFontSong_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop11 = {
   0x5916 /* first character */
  ,0x5916 /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFontSong_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop10 = {
   0x590D /* first character */
  ,0x590D /* last character  */
  ,&GUI_FontFontSong_CharInfo[ 10] /* address of first character */
  ,&GUI_FontFontSong_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop9 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  9] /* address of first character */
  ,&GUI_FontFontSong_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop8 = {
   0x53D7 /* first character */
  ,0x53D7 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  8] /* address of first character */
  ,&GUI_FontFontSong_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop7 = {
   0x5149 /* first character */
  ,0x5149 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  7] /* address of first character */
  ,&GUI_FontFontSong_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop6 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontFontSong_CharInfo[  6] /* address of first character */
  ,&GUI_FontFontSong_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop5 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  5] /* address of first character */
  ,&GUI_FontFontSong_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop4 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontFontSong_CharInfo[  4] /* address of first character */
  ,&GUI_FontFontSong_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop3 = {
   0x4EBA /* first character */
  ,0x4EBA /* last character  */
  ,&GUI_FontFontSong_CharInfo[  3] /* address of first character */
  ,&GUI_FontFontSong_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop2 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_FontFontSong_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontSong_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong_Prop1 = {
   0x4E00 /* first character */
  ,0x4E00 /* last character  */
  ,&GUI_FontFontSong_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSong_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSong_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

